name: Manuel Onay ile Test-Build-Deploy

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Deploy edilecek etiket (tag) adını girin (v1.1.1 formatında):'
        required: true
        default: 'v1.1.1'
      environment:
        description: 'Hangi ortama deploy edilecek?'
        required: true
        type: choice
        options:
          - production
          - pre-prod
        default: 'pre-prod'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref_name }}

  # - name: Checkout code manuel olarak
  #   run: |
  #     git clone https://github.com/${{ github.repository }}.git .
  #     git checkout ${{ github.event.inputs.tag || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist

  deploy-pre-prod:
    name: Deploy to pre-prod
    runs-on: ubuntu-latest
    needs: build
    if: (github.ref_name == 'main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'pre-prod')
    environment:
      name: pre-prod
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./dist

      - name: Deploy to GitHub Pages (Staging)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages-pre-prod 
          
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: (github.ref_type == 'tag' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    environment:
      name: production
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages